# Generated by Django 5.0.7 on 2024-07-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('passport_data', models.TextField(verbose_name='Паспортные Данные')),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('hours_worked', models.FloatField(verbose_name='Отработаннные часы работы')),
                ('total_hours_worked', models.FloatField(verbose_name='Полные часы работы')),
                ('deductions', models.FloatField(verbose_name='Удержание с ЗП')),
                ('total_earnings', models.FloatField(verbose_name='Совокупный Заработок')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Profitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_payment', models.FloatField(verbose_name='Оплата клиента')),
                ('employee_salary', models.FloatField(verbose_name='Зарплата клиента')),
                ('accommodation_payment', models.FloatField(verbose_name='Оплата проживания')),
                ('food_payment', models.FloatField(verbose_name='Оплата питания')),
                ('transport_payment', models.FloatField(verbose_name='Оплата транспорта')),
                ('agency_payment', models.FloatField(verbose_name='Оплата агенствам')),
                ('total_profitability', models.FloatField(verbose_name='Общая прибыль')),
                ('additional_expenses', models.FloatField(verbose_name='Дополнительные расходы')),
                ('fines', models.FloatField(verbose_name='Штрафы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability', to='api.employee')),
            ],
            options={
                'verbose_name': 'Рентабельность',
                'verbose_name_plural': 'Рентабельность',
            },
        ),
    ]
